### ISSUE TITLE
Three versions of experiment in a master App

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/ShinyBART#3]
We need to have Two version of ShinyBART

### Single player BART `ShinyBart_js.app`

1) Single player BART

### Competitive BART `ShinyBART_js_comp.app`

 The user specifies at the top a global game parameter. E.g.l `game.type = "comp.direct"`,  `game.type = "comp.lobby"`

2) Two players - enter opponent id
3) Two players - lobby

**Comment by ktrutmann** [comment]
Done
