### ISSUE TITLE
Get rid of barplot and only use line bars

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/ShinyBART#5]
- In point display. Make x axis go from game 1 to game.N for all plots.

- For practice game, just show one set of points with one x value (training).

- In the instructions prior to the real game start, show a blank graph and explain that the data will be shown for both you and your opponent after each round so they can see how they are doing relative to their opponent. In final label, include text "Final" (e.g.; 4 (Final))

**Comment by ktrutmann** [comment]
Done
